@startuml
scale 2
:开始;
partition 初始化 {
    :输入块数量/
    :构造并初始化内存及块]
    :输入页面请求序列/
    :构造并初始化请求列表]
}
partition 运行测试 {
    :初始化Optimal算法]
    :以Optimal算法进行测试|
    :初始化FIFO算法]
    :以FIFO算法进行测试|
    :初始化LRU算法]
    :以LRU算法进行测试|
}
:结束;
@enduml